[spacing.spacer.base]
"$value" = "1rem"

[size.dummy]
"$value" = "0"

[typography.font.family.sans.serif]
"$value" = ["Lato", "sans-serif"]

#TODO: Currently can't override the font family of display class
[typography.headings.font.family]
"$value" = ["Sora", "sans-serif"]

[typography.font.size.h2.base]
"$value" = "2.125rem"

[typography.font.size.h3.base]
"$value" = "1.875rem"

[typography.font.size.h4.base]
"$value" = "1.5rem"

[typography.font.size.h5.base]
"$value" = "1.25rem"

