[color.link.base]
"$value" = "#006C9A"

[color.primary.base]
"$value" = "#001e44"

[color.brand.base]
"$value" = "#276966"

[color.secondary.base]
"$value" = "#24bf96"

[color.success.base]
"$value" = "#1e4d4b"

[color.info.base]
"$value" = "#329be1"

[color.danger.base]
"$value" = "#c32d3a"

[color.warning.base]
"$value" = "#ffd900"

[color.light.base]
"$value" = "#f5f6fa"

[color.dark.base]
"$value" = "#1e4d4b"

[color.accent-b]
"$value" = "#276966"

[color.accent-a]
"$value" = "#001e44"

[color.headings.base]
"$value" = "{color.primary.base}"

[color.course.nav-menu.text]
"$value" = "#001e44"

