[wgu.color.text.main.navy]
"$value" = "{wgu.color.navy.base}"
[wgu.color.text.main.blue]
"$value" = "{wgu.color.blue.base}"
[wgu.color.text.main.lake]
"$value" = "{wgu.color.lake.base}"
[wgu.color.text.main.body]
"$value" = ""
[wgu.color.text.main.secondary]
"$value" = ""
[wgu.color.text.main.pure-white]
"$value" = ""
