[color.btn.bg.brand]
"$value" = "var(--wgu-color-btn-default)"

[color.btn.hover.bg.brand]
"$value" = "var(--wgu-color-btn-hover)"

[color.btn.active.bg.brand]
"$value" = "var(--wgu-color-btn-focus)"

[color.btn.focus.bg.brand]
"$value" = "var(--wgu-color-btn-focus)"

[color.btn.border.outline-brand]
"$value" = "var(--wgu-color-btn-default)"

[color.btn.hover.border.outline-brand]
"$value" = "var(--wgu-color-btn-hover)"

[color.btn.active.border.outline-brand]
"$value" = "var(--wgu-color-btn-focus)"

[color.btn.focus.border.outline-brand]
"$value" = "var(--wgu-color-btn-focus)"

