name: Verify
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v6

      - name: Setup and Build
        uses: ./.github/actions/build
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify token output unchanged
        run: |
          if ! git diff --exit-code; then
            echo "There are unexpected changes in ./paragon/css. These changes need to be committed."
            echo "Please run 'npm run build-tokens' and commit the changes"
            exit 1
          fi

      - name: Build
        run: npm run build
