name: Build and Deploy

on:
  pull_request:
    branches:
      - "*-release/**"

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup and Build
        uses: ./.github/actions/build
        with:
          node-version: 24

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          deploy-path: pr/${{ github.event.pull_request.number }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_REGION }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-endpoint: ${{ vars.S3_ENDPOINT }}
